name: Linters

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  lint:
    name: Check Linter Errors
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: '26.0'
        elixir-version: '1.16.0'
        
    - name: Install dependencies
      run: mix deps.get
      
    - name: Run Credo
      run: mix credo --strict
